const TEST_INCREMENT = 'TEST_INCREMENT';
const TEST_DECREMENT = 'TEST_DECREMENT';

const COUNTRY_CODE_CHANGE = 'COUNTRY_CODE_CHANGE';

const SET_MAIN_PAGE_DATA = 'SET_MAIN_PAGE_DATA';

export {
    TEST_INCREMENT,
    TEST_DECREMENT,

    COUNTRY_CODE_CHANGE,

    SET_MAIN_PAGE_DATA,
};