const TEST_INCREMENT = 'TEST_INCREMENT';
const TEST_DECREMENT = 'TEST_DECREMENT';

const COUNTRY_CODE_CHANGE = 'COUNTRY_CODE_CHANGE';

const SET_MAIN_PAGE_DATA = 'SET_MAIN_PAGE_DATA';
const ADD_MAIN_PAGE_DATA = 'ADD_MAIN_PAGE_DATA';
const SET_GLOBAL_TYPE_DATA = 'SET_GLOBAL_TYPE_DATA';
const SET_NOW_GLOBAL_TYPE = 'SET_NOW_GLOBAL_TYPE';
const SET_MAIN_CONTENT_PAGE_INFO = 'SET_MAIN_CONTENT_PAGE_INFO';

const SET_VIDEO_FULL_DATA = 'SET_VIDEO_FULL_DATA';
const REFRESH_VIDEO_RECOMMEND_NEGATIVE_DATA = 'REFRESH_VIDEO_RECOMMEND_NEGATIVE_DATA';
const SET_EPISCODE_SOURCE = 'SET_EPISCODE_SOURCE';
const SET_GUESS_LIKE_SOURCE = 'SET_GUESS_LIKE_SOURCE';
const SET_COMMENT_LIST_DATA = 'SET_COMMENT_LIST_DATA';

const SET_VIDEO_URL_AND_TYPE = 'SET_VIDEO_URL_AND_TYPE';

export {
    TEST_INCREMENT,
    TEST_DECREMENT,

    COUNTRY_CODE_CHANGE,

    SET_MAIN_PAGE_DATA,
    ADD_MAIN_PAGE_DATA,
    SET_GLOBAL_TYPE_DATA,
    SET_NOW_GLOBAL_TYPE,
    SET_MAIN_CONTENT_PAGE_INFO,

    SET_VIDEO_FULL_DATA,
    REFRESH_VIDEO_RECOMMEND_NEGATIVE_DATA,
    SET_EPISCODE_SOURCE,
    SET_GUESS_LIKE_SOURCE,
    SET_COMMENT_LIST_DATA,

    SET_VIDEO_URL_AND_TYPE,
};