const NAVI_BGCOLOR = 'rgb(51,57,62)';
const SCREEN_BGCOLOR = 'rgb(33,44,50)';
const NAVI_ACTIVE_TINT_COLOR = 'rgb(254,163,91)';
const NAVI_DEFAULT_TINT_COLOR = 'rgb(153,153,153)';
const SAFE_AREA_BGCOLOR = 'white';

const HEADER_TITLE_COLOR = NAVI_ACTIVE_TINT_COLOR;
const DEFAULT_TEXT_COLOR = 'rgb(151,151,151)';
export {
    NAVI_BGCOLOR,
    SCREEN_BGCOLOR,
    NAVI_ACTIVE_TINT_COLOR,
    NAVI_DEFAULT_TINT_COLOR,
    SAFE_AREA_BGCOLOR,

    HEADER_TITLE_COLOR,
    DEFAULT_TEXT_COLOR
};