const NAVI_BGCOLOR = 'rgb(51,57,62)';
const SCREEN_BGCOLOR = 'rgb(33,44,50)';
const NAVI_ACTIVE_TINT_COLOR = 'rgb(240,190,65)';
const NAVI_DEFAULT_TINT_COLOR = '#909090';
const SAFE_AREA_BGCOLOR = 'white';
export {
    NAVI_BGCOLOR,
    SCREEN_BGCOLOR,
    NAVI_ACTIVE_TINT_COLOR,
    NAVI_DEFAULT_TINT_COLOR,
    SAFE_AREA_BGCOLOR,
};