const NAVI_BGCOLOR = 'rgb(250,250,250)';
const NAVI_ACTIVE_TINT_COLOR = 'rgb(46,122,246)';
const NAVI_DEFAULT_TINT_COLOR = '#909090';
const SAFE_AREA_BGCOLOR = 'rgb(31,16,9)';
export {
    NAVI_BGCOLOR,
    NAVI_ACTIVE_TINT_COLOR,
    NAVI_DEFAULT_TINT_COLOR,
    SAFE_AREA_BGCOLOR,
};