import { Dimensions } from 'react-native';

const DEVICE_HEIGHT = Dimensions.get('window').height;
const DEVICE_WIDTH = Dimensions.get('window').width;

const ICON_BTN_WITH_TITLE_CONTAINER_WIDTH = 60;

//ImageAvater
const IMAGE_AVATER_VER_WIDTH = (DEVICE_WIDTH - 6) / 3;
const IMAGE_AVATER_VER_HEIGHT = 1.5 * IMAGE_AVATER_VER_WIDTH;
const IMAGE_AVATER_HO_WIDTH = (DEVICE_WIDTH - 4) / 2;
const IMAGE_AVATER_HO_HEIGHT = IMAGE_AVATER_HO_WIDTH / 1.5;

export {
    DEVICE_HEIGHT,
    DEVICE_WIDTH,
    ICON_BTN_WITH_TITLE_CONTAINER_WIDTH,

    IMAGE_AVATER_VER_WIDTH,
    IMAGE_AVATER_VER_HEIGHT,
    IMAGE_AVATER_HO_WIDTH,
    IMAGE_AVATER_HO_HEIGHT,
};